services:
  # php
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel:/var/www
    networks:
      - hortmann-cars

  # vite
  vite:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - hortmann-cars

  # nginx
  laravel-nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./laravel/storage/app/public:/var/www/storage/app/public
      - ./laravel/public:/var/www/public
    networks:
      - hortmann-cars

  # db mysql
  database:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3301:3306"
    networks:
      - hortmann-cars

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - hortmann-cars

networks:
  hortmann-cars:
    driver: bridge
